version: "3"
services:
  nginx:
    container_name: ${LEMP_NGINX_NAME}
    image: nginx:1.17.6-alpine
    volumes:
      - $PWD:/var/www/html
      - $PWD/docker/ssl:/etc/ssl
      - $PWD/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - $PWD/docker/nginx/self-signed.conf:/etc/nginx/self-signed.conf:ro
      - $PWD/docker/nginx/ssl-params.conf:/etc/nginx/ssl-params.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php

  php:
    container_name: ${LEMP_PHP_NAME}
    build: docker/php
    user: 1000:1000
    volumes:
      - $PWD:/var/www/html
    working_dir: /var/www/html

  db:
    container_name: ${LEMP_DB_NAME}
    image: mysql:8.0.18
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
#      - ./docker/mariadb/dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - default

volumes:
  persistent:
