version: "3"
services:
  nginx:
    container_name: ${APP_NAME}_nginx
    image: nginx:alpine
    volumes:
      - $PWD:/var/www/html
      - $PWD/docker/ssl:/etc/ssl
      - $PWD/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - $PWD/docker/nginx/self-signed.conf:/etc/nginx/self-signed.conf:ro
      - $PWD/docker/nginx/ssl-params.conf:/etc/nginx/ssl-params.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
  php:
    user: '${HOST_USER_ID}:${HOST_GROUP_ID}'
    container_name: ${APP_NAME}_php
    build:
      context: docker/php
      args:
        APP_USER_ID: '${HOST_USER_ID}'
        APP_GROUP_ID: '${HOST_GROUP_ID}'
    volumes:
      - $PWD:/var/www/html
    working_dir: /var/www/html
    environment:
      APACHE_RUN_USER: '#${HOST_USER_ID}'
      APACHE_RUN_GROUP: '#${HOST_GROUP_ID}'
      PHP_IDE_CONFIG: 'serverName=${SERVER_NAME}'
    depends_on:
      - db
  db:
    container_name: ${APP_NAME}_db
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - persistent:/var/lib/mysql
    networks:
      - default

volumes:
  persistent:
